# Generated by Django 2.2.5 on 2019-09-03 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.CharField(max_length=256)),
                ('y_pos', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('airborne', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_point', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('flight', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='flightseats.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('seat', models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='flightseats.Seat')),
            ],
        ),
    ]
